### ISSUE TITLE
A little help

### ISSUE THREAD

**Issue by Krator3** [Zproger/GenesisNvim#10]
Hello! I looked at your configuration and noticed that in many places it is quite small and poor. Here's a link to my config:
https://github.com/Krator3/FixVim
I hope you'll watch it and take something useful for your build. Good luck!
P.S: I won’t refuse a star)

---
Здравствуйте! Я посмотрел вашу конфигурацию и заметил, что во многих местах она довольно маленькая и бедная. Вот ссылка на мой конфиг:
https://github.com/Krator3/FixVim
Надеюсь, вы посмотрите его и возьмёте что-нибудь полезное для своей сборки.  Удачи!
P.S: От звезды не откажусь)

**Comment by Zproger** [comment]
Здравствуйте, основная цель проекта быть максимально легким и минималистичным инструментом, но все же спасибо за то, что поделились своим проектом, я обязательно проанализирую код, который вы предоставили и поставлю звездочку когда руки дойдут до обновления nvim 🙏
