### ISSUE TITLE
Ошибка при открытии файла с Git

### ISSUE THREAD

**Issue by Solarmove** [Zproger/GenesisNvim#4]
![image](https://github.com/Zproger/GenesisNvim/assets/109293651/c7cc167e-9122-41ff-9bed-f4eb1bbd1660)
Нажал d - такая ошибка
Windows 10

**Comment by kuprTheMan** [comment]
That's right, you used the Git functionality in a non-Git repository

**Comment by kuprTheMan** [comment]
The error says that the current directory is not a Git directory. If you use the same function in a Git repository, then everything will work

**Comment by Zproger** [comment]
Для решения используйте WSL как указано в Issue #5 .
