### ISSUE TITLE
Mason не устанавливает все автоматом

### ISSUE THREAD

**Issue by maxktz** [Zproger/GenesisNvim#7]
Я не знаю проблема ли это, но мейсон почему то у меня ничего сам не установил, пришлось lsp ставить вручную, 

плюс нет команды MasonInstallAll не работает, я юзал NvChad, там работала.

**Comment by Zproger** [comment]
Скорее всего функция `MasonInstallAll` реализована в NvChad самостоятельно. Попробуйте выполнить эту команду напрямую и дождаться пока загрузятся все модули: `nvim -c "MasonInstall pyright ruff-lsp mypy"`.

Если не сработает, тогда зайдите в nvim, далее пропишите `:Mason` и попробуйте вручную найти `pyright` и прочие модули и установить их. Вполне реально что не хватает какой-то зависимости, например `npm`, поэтому идет сброс.

**Comment by maxktz** [comment]
Хорошо, не увидел в readme `nvim -c "MasonInstall pyright ruff-lsp mypy"`, моя ошибка.

**Comment by Ninzalo** [comment]
[Пример](https://github.com/Ninzalo/nvimconf/blob/a46355e9b07dd1182aa162a1ce59d1b623778822/lua/plugins/mason-lspconfig.lua) реализации автоустановки Mason плагинов с помощью `mason-lspconfig` и `mason-tool-installer`
