### ISSUE TITLE
Не работает Open Terminal <leader>+s

### ISSUE THREAD

**Issue by maxktz** [Zproger/GenesisNvim#8]
Нажимаешь Open Terminal, он на миллисекунду открывается и сразу сам закроется, только моргнет.

Ничего не менял, первый запуск. 

Команда ToggleTerm тоже не открывает его, он просто моргает и закрывается

![image](https://github.com/Zproger/GenesisNvim/assets/109878406/62810993-972e-4ed1-aa90-4be61b23cf4f)

**Comment by Zproger** [comment]
У вас установлен `fish`? И какой вывод от `which fish`?

**Comment by maxktz** [comment]
Пофиксил! У меня zsh!, но помогает и просто убрать эту строчку, автоматически определяется.

![image](https://github.com/Zproger/GenesisNvim/assets/109878406/5c4a313e-9084-4912-bac7-a6ae8b995793)
