### ISSUE TITLE
You need to rewrite the Lazy logic in the config.

### ISSUE THREAD

**Issue by kuprTheMan** [Zproger/GenesisNvim#9]
Lazy can read plugins directly from the file, it is wrong to describe each plugin in plugins.lua as you did. In this file you should write the path to the directory with plugin configs, and in each plugin file there should be a return to which the attributes are written (plugin name and author name, lazyload mode and the plugin config itself, written in config = function()) so you get not only a more correct structure through which you can add and remove plugins more easily, but you can also use lazyload for plugins.

Since you're using Lazy, it doesn't make any sense, because now you're not using any of the features it provides and you're simply overloading the system with such a powerful batch loader. If you want to continue using the structure you have now, it is better to use Packer instead of Lazy.

**Comment by kuprTheMan** [comment]
Also, you will no longer need to import each plugin's config into init.lua

**Comment by Zproger** [comment]
Thanks for your input, I've added this to the list of updates and will definitely rewrite the config. I'm closing the issue for now.

**Comment by kuprTheMan** [comment]
Sigma
